src/config/routes.rb
Rails.application.routes.draw do
  resources :cerimonie

  resources :distintivi

  resources :servizi

  resources :censimenti

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :soci

  root 'home#index'

  resources :notizie
  resources :unita
  resources :soci, only: [:show]
end

src/app/controllers/cerimonie_controller.rb
class CerimonieController < ApplicationController
  before_action :set_cerimonia, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cerimonie = Cerimonia.all
    respond_with(@cerimonie)
  end

  def show
    respond_with(@cerimonia)
  end

  def new
    @cerimonia = Cerimonia.new
    respond_with(@cerimonia)
  end

  def edit
  end

  def create
    @cerimonia = Cerimonia.new(cerimonia_params)
    @cerimonia.save
    respond_with(@cerimonia)
  end

  def update
    @cerimonia.update(cerimonia_params)
    respond_with(@cerimonia)
  end

  def destroy
    @cerimonia.destroy
    respond_with(@cerimonia)
  end

  private
    def set_cerimonia
      @cerimonia = Cerimonia.find(params[:id])
    end

    def cerimonia_params
      params.require(:cerimonia).permit(:socio_id, :distintivo_id, :data)
    end
end

src/app/helpers/cerimonie_helper.rb
module CerimonieHelper
end

src/app/views/cerimonie/_form.html.erb
<%= form_for(@cerimonia) do |f| %>
  <% if @cerimonia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cerimonia.errors.count, "error") %> prohibited this cerimonia from being saved:</h2>

      <ul>
      <% @cerimonia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :socio_id %><br>
    <%= f.text_field :socio_id %>
  </div>
  <div class="field">
    <%= f.label :distintivo_id %><br>
    <%= f.text_field :distintivo_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/cerimonie/edit.html.erb
<h1>Editing cerimonia</h1>

<%= render 'form' %>

<%= link_to 'Show', @cerimonia %> |
<%= link_to 'Back', cerimonie_path %>

src/app/views/cerimonie/index.html.erb
<h1>Listing cerimonie</h1>

<table>
  <thead>
    <tr>
      <th>Socio</th>
      <th>Distintivo</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cerimonie.each do |cerimonia| %>
      <tr>
        <td><%= cerimonia.socio %></td>
        <td><%= cerimonia.distintivo %></td>
        <td><%= cerimonia.data %></td>
        <td><%= link_to 'Show', cerimonia %></td>
        <td><%= link_to 'Edit', edit_cerimonia_path(cerimonia) %></td>
        <td><%= link_to 'Destroy', cerimonia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cerimonia', new_cerimonia_path %>

src/app/views/cerimonie/new.html.erb
<h1>New cerimonia</h1>

<%= render 'form' %>

<%= link_to 'Back', cerimonie_path %>

src/app/views/cerimonie/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Socio:</strong>
  <%= @cerimonia.socio %>
</p>

<p>
  <strong>Distintivo:</strong>
  <%= @cerimonia.distintivo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @cerimonia.data %>
</p>

<%= link_to 'Edit', edit_cerimonia_path(@cerimonia) %> |
<%= link_to 'Back', cerimonie_path %>