src/config/routes.rb
Rails.application.routes.draw do
  resources :cerimonie

  resources :distintivi

  resources :servizi

  resources :censimenti

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :soci

  root 'home#index'

  resources :notizie
  resources :unita
  resources :soci, only: [:show]
end

src/app/controllers/distintivi_controller.rb
class DistintiviController < ApplicationController
  before_action :set_distintivo, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @distintivi = Distintivo.all
    respond_with(@distintivi)
  end

  def show
    respond_with(@distintivo)
  end

  def new
    @distintivo = Distintivo.new
    respond_with(@distintivo)
  end

  def edit
  end

  def create
    @distintivo = Distintivo.new(distintivo_params)
    @distintivo.save
    respond_with(@distintivo)
  end

  def update
    @distintivo.update(distintivo_params)
    respond_with(@distintivo)
  end

  def destroy
    @distintivo.destroy
    respond_with(@distintivo)
  end

  private
    def set_distintivo
      @distintivo = Distintivo.find(params[:id])
    end

    def distintivo_params
      params.require(:distintivo).permit(:nome)
    end
end

src/app/helpers/distintivi_helper.rb
module DistintiviHelper
end

src/app/views/distintivi/_form.html.erb
<%= form_for(@distintivo) do |f| %>
  <% if @distintivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distintivo.errors.count, "error") %> prohibited this distintivo from being saved:</h2>

      <ul>
      <% @distintivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/distintivi/edit.html.erb
<h1>Editing distintivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @distintivo %> |
<%= link_to 'Back', distintivi_path %>

src/app/views/distintivi/index.html.erb
<h1>Listing distintivi</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distintivi.each do |distintivo| %>
      <tr>
        <td><%= distintivo.nome %></td>
        <td><%= link_to 'Show', distintivo %></td>
        <td><%= link_to 'Edit', edit_distintivo_path(distintivo) %></td>
        <td><%= link_to 'Destroy', distintivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distintivo', new_distintivo_path %>

src/app/views/distintivi/new.html.erb
<h1>New distintivo</h1>

<%= render 'form' %>

<%= link_to 'Back', distintivi_path %>

src/app/views/distintivi/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @distintivo.nome %>
</p>

<%= link_to 'Edit', edit_distintivo_path(@distintivo) %> |
<%= link_to 'Back', distintivi_path %>