src/config/routes.rb
Rails.application.routes.draw do
  resources :cerimonie

  resources :distintivi

  resources :servizi

  resources :censimenti

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :soci

  root 'home#index'

  resources :notizie
  resources :unita
  resources :soci, only: [:show]
end

src/app/models/branca.rb
class Branca < ActiveRecord::Base
  has_many :unita,      inverse_of: :branca
  has_many :distintivi, inverse_of: :branca

  validates   :nome,       presence: true
  validates   :nome_unita, presence: true
end

src/app/controllers/notizie_controller.rb
class NotizieController < ApplicationController
  before_action :set_notizia, only: [:show, :edit, :update, :destroy]

  # GET /notizie
  # GET /notizie.json
  def index
    @notizie = Notizia.all
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /notizie/1
  # GET /notizie/1.json
  def show
  end

  # GET /notizie/new
  def new
    @notizia = Notizia.new
  end

  # GET /notizie/1/edit
  def edit
  end

  # POST /notizie
  # POST /notizie.json
  def create
    @notizia = Notizia.new(notizia_params)

    respond_to do |format|
      if @notizia.save
        format.html { redirect_to @notizia, notice: 'Notizia was successfully created.' }
        format.json { render :show, status: :created, location: @notizia }
      else
        format.html { render :new }
        format.json { render json: @notizia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notizie/1
  # PATCH/PUT /notizie/1.json
  def update
    respond_to do |format|
      if @notizia.update(notizia_params)
        format.html { redirect_to @notizia, notice: 'Notizia was successfully updated.' }
        format.json { render :show, status: :ok, location: @notizia }
      else
        format.html { render :edit }
        format.json { render json: @notizia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notizie/1
  # DELETE /notizie/1.json
  def destroy
    @notizia.destroy
    respond_to do |format|
      format.html { redirect_to notizie_url, notice: 'Notizia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notizia
      @notizia = Notizia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notizia_params
      params.require(:notizia).permit(:title, :text, { :unita_ids => [] })
    end
end

src/app/helpers/notizie_helper.rb
module NotizieHelper
end

src/app/views/notizie/_form.html.erb
<%= form_for(@notizia) do |f| %>
  <% if @notizia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notizia.errors.count, "error") %> prohibited this notizia from being saved:</h2>

      <ul>
      <% @notizia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, required: true, class:'form_title' %>
  </div>
  <div class="field">
    <%= f.text_area :text, required: true, class: "redactor" %>
  </div>
  <div class="field">
    <%= f.label :unita_ids, "Unità" %><br>
    <%= f.select :unita_ids,
      Unita.all.map { |u| [ u.branca.nome + " - " + u.nome_completo, u.id] },
      { selected: @notizia.unita.collect(&:id) },
      { class: 'chosen-select', multiple: true, 'data-placeholder' => 'Seleziona...' }
    %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/notizie/_notizia.html.erb
    <tr>
      <td><%= link_to notizia.title, notizia %></td>
    </tr>

src/app/views/notizie/edit.html.erb
<h1>Editing notizia</h1>

<%= render 'form' %>

<%= link_to 'Show', @notizia %> |
<%= link_to 'Back', notizie_path %>

src/app/views/notizie/index.html.erb
<h1>Elenco Notizie</h1>

<table>
  <tbody>
    <% @notizie.each do |notizia| %>
      <tr>
        <td><%= link_to notizia.title, notizia %></td>
        <td><%= link_to 'Edit', edit_notizia_path(notizia) %></td>
        <td><%= link_to 'Destroy', notizia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notizia', new_notizia_path %>

src/app/views/notizie/new.html.erb
<h1>New notizia</h1>

<%= render 'form' %>

<%= link_to 'Back', notizie_path %>

src/app/views/notizie/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @notizia.title %>
</h1>

<p>
  <%= @notizia.text.html_safe %>
</p>

<% if !@notizia.unita.empty? %>
  <p> Unità:
    <% @notizia.unita.each_with_index do |u, i| %>
      <% if i > 0 %>
        |
      <% end %>
      <%= link_to u.nome_completo, u %>
    <% end %>
  </p>
<% end %>

<%= link_to 'Edit', edit_notizia_path(@notizia) %> |
<%= link_to 'Back', notizie_path %>