src/config/routes.rb
Rails.application.routes.draw do
  resources :cerimonie

  resources :distintivi

  resources :servizi

  resources :censimenti

  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :soci

  root 'home#index'

  resources :notizie
  resources :unita
  resources :soci, only: [:show]
end

src/app/models/unita.rb
class Unita < ActiveRecord::Base
  belongs_to  :branca, inverse_of: :unita
  has_many    :censimenti, inverse_of: :unita
  has_many    :soci, through: :censimenti
  has_many    :servizi, inverse_of: :unita
  has_many    :capi,
    -> { where servizio: { capo: true } },
    class_name: "Socio",
    source: :socio,
    through: :servizi
  has_many :aiuti,
    -> { where servizio: { capo: [false, nil] } },
    through: :servizi,
    class_name: "Socio",
    source: :socio
  has_and_belongs_to_many :notizie

  validates :nome, presence: true

  extend FriendlyId
  friendly_id :nome, use: :slugged

  def nome_completo
    branca.nome_unita + " " + nome
  end

  def staff(a = AnnoScout.current.to_i)
    {
      # references() serve a poter effettuare il successivo where()
      "capo" => self.capi.references(:servizi).where(servizio: { anno: a } ).first,
      "aiuti" => self.aiuti.references(:servizi).where(servizio: { anno: a } )
    }
  end
end

src/app/controllers/unita_controller.rb
class UnitaController < ApplicationController
  before_action :set_unita, only: [:show, :edit, :update, :destroy]

  # GET /unita
  # GET /unita.json
  def index
    @unita = Unita.all
  end

  # GET /unita/1
  # GET /unita/1.json
  def show
  end

  # GET /unita/new
  def new
    @unita = Unita.new
  end

  # GET /unita/1/edit
  def edit
  end

  # POST /unita
  # POST /unita.json
  def create
    @unita = Unita.new(unita_params)

    respond_to do |format|
      if @unita.save
        format.html { redirect_to @unita, notice: 'Unita was successfully created.' }
        format.json { render :show, status: :created, location: @unita }
      else
        format.html { render :new }
        format.json { render json: @unita.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unita/1
  # PATCH/PUT /unita/1.json
  def update
    respond_to do |format|
      if @unita.update(unita_params)
        format.html { redirect_to @unita, notice: 'Unita was successfully updated.' }
        format.json { render :show, status: :ok, location: @unita }
      else
        format.html { render :edit }
        format.json { render json: @unita.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unita/1
  # DELETE /unita/1.json
  def destroy
    @unita.destroy
    respond_to do |format|
      format.html { redirect_to unita_index_url, notice: 'Unita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unita
      @unita = Unita.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unita_params
      params.require(:unita).permit(:nome, :branca_id)
    end
end

src/app/helpers/unita_helper.rb
module UnitaHelper
end

src/app/views/unita/_form.html.erb
<%= form_for(@unita) do |f| %>
  <% if @unita.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unita.errors.count, "error") %> prohibited this unita from being saved:</h2>

      <ul>
      <% @unita.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :branca_id %><br>
    <%= f.text_field :branca_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/unita/edit.html.erb
<h1>Editing unita</h1>

<%= render 'form' %>

<%= link_to 'Show', @unita %> |
<%= link_to 'Back', unita_index_path %>

src/app/views/unita/index.html.erb
<h1>Listing unita</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Branca</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unita.each do |unita| %>
      <tr>
        <td><%= unita.nome %></td>
        <td><%= unita.branca %></td>
        <td><%= link_to 'Show', unita %></td>
        <td><%= link_to 'Edit', edit_unita_path(unita) %></td>
        <td><%= link_to 'Destroy', unita, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unita', new_unita_path %>

src/app/views/unita/new.html.erb
<h1>New unita</h1>

<%= render 'form' %>

<%= link_to 'Back', unita_index_path %>

src/app/views/unita/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @unita.nome_completo %>
</h1>

<%= link_to 'Edit', edit_unita_path(@unita) %> |
<%= link_to 'Back', unita_index_path %>